apiVersion: v1
kind: ConfigMap
metadata:
  name: merge-sentinel-config
data:
  DISKCACHE_DIR: /data
  WEBHOOK_DB_PATH: /data/webhooks.sqlite3
  OVERRIDE_LOGGING: WARNING
  PR_TIMEOUT: "10"
  WORKER_SLEEP: "1"
  ACCESS_TOKEN_TTL: "300"
  PRS_TTL: "60"
  DRY_RUN: "false"
  CHECK_RUN_DEBOUNCE_WINDOW: "3600"
  PROCESS_START_PAUSE: "5"
  INDEX_REDIRECT_URL: "https://home.cern"
  WEBHOOK_DB_ENABLED: "true"
  WEBHOOK_DB_RETENTION_DAYS: "30"
  WEBHOOK_DB_EVENTS: check_run,check_suite,workflow_run,status,pull_request
  WEBHOOK_DISPATCH_ENABLED: "false"
  WEBHOOK_PROJECTION_PRUNE_ENABLED: "true"
  WEBHOOK_PROJECTION_COMPLETED_RETENTION_SECONDS: "604800"
  WEBHOOK_PROJECTION_ACTIVE_RETENTION_SECONDS: "2592000"
  WEBHOOK_FILTER_SELF_APP_ID: "true"
  WEBHOOK_FILTER_APP_IDS: "29196"
  PROJECTION_EVAL_ENABLED: "true"
  PROJECTION_PUBLISH_ENABLED: "true"
  PROJECTION_DEBOUNCE_SECONDS: "2"
  PROJECTION_PULL_REQUEST_SYNCHRONIZE_DELAY_SECONDS: "30"
  PROJECTION_CHECK_RUN_NAME: merge-sentinel
  PROJECTION_CONFIG_CACHE_SECONDS: "300"
  PROJECTION_PR_FILES_CACHE_SECONDS: "86400"
  PROJECTION_PATH_RULE_FALLBACK_ENABLED: "true"
